name: minimal
channels:
- conda-forge
- anaconda
dependencies:
- python=3.9.13
- pip
- rdkit=2020.09.5
- pip:
  - azureml-inference-server-http==1.4.0
  - pandas~=1.3.0
  - scikit-learn
  - azureml-core
  - azureml-dataset-runtime[pandas,fuse]